[install]
cmd = 'apt install -y git python3 gcc build-essential && node -v  && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && nvm use 18 && node -v && npm install -g @soketi/soketi'

[start]
cmd = 'npm run start'
